

[package]
name = "tx_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ethereum-types = "0.14"  
clap = { version = "4.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
